services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drivenow
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////app/data/drivenow.db
    volumes:
      - ./data:/app/data
